const baseeic = {
    name: 'null',
    hp: null,
    baseDMG: null,
    top: null,
    left: null,
    imageURL: 'null',
    rage: null
}

export const ASSETS = {
    Dwarfs: {
        base: './images/Dwarfs.png',
        Urvald: {
            unitType: 'RageUnit',
            name: 'Urvald',
            hp: 300,
            baseDMG: 25,
            top: 2,
            left: 3,
            imageURL: './images/Urvald.png',
        },
        Herion: {
            unitType: 'RageUnit',
            name: 'Herion',
            hp: 300,
            baseDMG: 20,
            top: 2,
            left: 6,
            imageURL: './images/Herion.png',
        },
        Axtom: {
            unitType: 'RageUnit',
            name: 'Axtom',
            hp: 300,
            baseDMG: 30,
            top: 2,
            left: 6,
            imageURL: './images/Axtom.png',
        },
        Korvuld: {
            unitType: 'RageUnit',
            name: 'Korvuld',
            hp: 300,
            baseDMG: 30,
            top: 2,
            left: 4,
            imageURL: './images/Korvuld.png',
        },
        Mormond: {
            unitType: 'RageUnit',
            name: 'Mormond',
            hp: 340,
            baseDMG: 27,
            top: 2,
            left: 5,
            imageURL: './images/Mormond.png',
        },
        Qamok: {
            unitType: 'RageUnit',
            name: 'Qamok',
            hp: 200,
            baseDMG: 45,
            top: 2,
            left: 7,
            imageURL: './images/Qamok.png',
        }
    },
    Elves: {
        base: './images/Elves.png',
        Euvion: {
            unitType: 'ManaUnit',
            name: 'Euvion',
            hp: 300,
            baseDMG: 30,
            top: 5,
            left: 2,
            imageURL: './images/Euvion.png',
        },
        Lemro: {
            unitType: 'ManaUnit',
            name: 'Lemro',
            hp: 300,
            baseDMG: 30,
            top: 5,
            left: 3,
            imageURL: './images/Lemro.png',
        },
        Xavius: {
            unitType: 'ManaUnit',
            name: 'Xavius',
            hp: 300,
            baseDMG: 35,
            top: 5,
            left: 4,
            imageURL: './images/Xavius.png'
        },
        Lotnom: {
            unitType: 'ManaUnit',
            name: 'Lotnom',
            hp: 330,
            baseDMG: 30,
            top: 5,
            left: 5,
            imageURL: './images/Lotnom.png',
        },
        Sorcela: {
            unitType: 'ManaUnit',
            name: 'Sorcela',
            hp: 300,
            baseDMG: 30,
            top: 5,
            left: 6,
            imageURL: './images/Sorcela.png',
        },
        Rengela: {
            unitType: 'ManaUnit',
            name: 'Rengela',
            hp: 300,
            baseDMG: 35,
            top: 5,
            left: 8,
            imageURL: './images/Rengela.png',
        }
    },
    Orcs: {
        base: './images/Orcs.png',
        Korgok: {
            unitType: 'EnergyUnit',
            name: 'Korgok',
            hp: 400,
            baseDMG: 40,
            top: 3,
            left: 8,
            imageURL: './images/Korgok.png',
        },
        Gromgash: {
            unitType: 'RageUnit',
            name: 'Gromgash',
            hp: 400,
            baseDMG: 40,
            top: 3,
            left: 4,
            imageURL: './images/Gromgash.png',
        },
        Rorok: {
            unitType: 'RageUnit',
            name: 'Rorok',
            hp: 400,
            baseDMG: 40,
            top: 3,
            left: 5,
            imageURL: './images/Rorok.png',
        },
        Zizim: {
            unitType: 'EnergyUnit',
            name: 'Zizim',
            hp: 400,
            baseDMG: 40,
            top: 4,
            left: 4,
            imageURL: './images/Zizim.png',
        },
        Orcom: {
            unitType: 'RageUnit',
            name: 'Orcom',
            hp: 400,
            baseDMG: 40,
            top: 3,
            left: 6,
            imageURL: './images/Orcom.png',
        },
        Orok: {
            unitType: 'RageUnit',
            name: 'Orok',
            hp: 400,
            baseDMG: 40,
            top: 7,
            left: 4,
            imageURL: './images/Orok.png',
        },
    },
    Humans: {
        base: './images/Humans.png',
        Daimion: {
            unitType: 'RageUnit',
            name: 'Daimion',
            hp: 400,
            baseDMG: 40,
            top: 7,
            left: 6,
            imageURL: './images/Daimion.png',
        },
        Eonar: {
            unitType: 'EnergyUnit',
            name: 'Eonar',
            hp: 400,
            baseDMG: 40,
            top: 7,
            left: 6,
            imageURL: './images/Eonar.png',
        },
        Lightum: {
            unitType: 'ManaUnit',
            name: 'Lightum',
            hp: 400,
            baseDMG: 40,
            top: 7,
            left: 4,
            imageURL: './images/Lightum.png',
        },
        Polonom: {
            unitType: 'RageUnit',
            name: 'Polonom',
            hp: 460,
            baseDMG: 40,
            top: 9,
            left: 7,
            imageURL: './images/Polonom.png',
        },
        Medeev: {
            unitType: 'ManaUnit',
            name: 'Medeev',
            hp: 270,
            baseDMG: 50,
            top: 1,
            left: 5,
            imageURL: './images/Medeev.png',
        },
        Jerom: {
            unitType: 'EnergyUnit',
            name: 'Jerom',
            hp: 300,
            baseDMG: 40,
            top: 2,
            left: 8,
            imageURL: './images/Jerom.png',
        }
    },
    Undeads: {
        base: './images/Undeads.png',
        Amon: {
            unitType: 'RageUnit',
            name: 'Amon',
            hp: 400,
            baseDMG: 40,
            top: 8,
            left: 5,
            imageURL: './images/Amon.png',
        },
        Feror: {
            unitType: 'RageUnit',
            name: 'Feror',
            hp: 400,
            baseDMG: 40,
            top: 2,
            left: 7,
            imageURL: './images/Feror.png',
        },
        Gbok: {
            unitType: 'RageUnit',
            name: 'Gbok',
            hp: 400,
            baseDMG: 40,
            top: 4,
            left: 7,
            imageURL: './images/Gbok.png',
        },
        Ipem: {
            unitType: 'RageUnit',
            name: 'Ipem',
            hp: 400,
            baseDMG: 40,
            top: 3,
            left: 4,
            imageURL: './images/Ipem.png',
        },
        Polom: {
            unitType: 'RageUnit',
            name: 'Polom',
            hp: 400,
            baseDMG: 40,
            top: 6,
            left: 5,
            imageURL: './images/Polom.png',
        },
        Vezon: {
            unitType: 'RageUnit',
            name: 'Vezon',
            hp: 400,
            baseDMG: 40,
            top: 1,
            left: 4,
            imageURL: './images/Vezon.png',
        }
    }
};
